name: pyqwen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - matplotlib
  - huggingface_hub
  - transformers>=5.12.0
  - accelerate
  - optimum
  - evaluate
  - datasets
  - scikit-learn
  - jupyterlab
  - ipykernel
  - ipywidgets
  - tqdm
  - optuna
  - pandas
  - seaborn
  - pysoundfile
  - librosa
  - num2words
  - setuptools
  - peft
  - trl>=1.7.0
  - pytorch=2.12
  - torchaudio
  - torchvision
  - wandb
  - pip:
      - bitsandbytes
      - mistral-common[audio,hf-hub]
      - https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.9.17/flash_attn-2.8.3+cu132torch2.12-cp312-cp312-linux_x86_64.whl
