name: pyqwen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - mamba
  - torchvision
  - torchaudio
  - pytorch-gpu=2.9.1
  - numpy
  - matplotlib
  - transformers
  - accelerate
  - evaluate
  - flash-attn
  - bitsandbytes
  - datasets
  - scikit-learn
  - notebook
  - ipykernel
  - ipywidgets
  - widgetsnbextension
  - jupyterlab
  - jupyterlab_widgets
  - tqdm
  - torchinfo
  - optuna
  - pandas-stubs
  - pandas
  - seaborn
  - pysoundfile
  - librosa
  - num2words
  - wandb
  - nvidia::cuda-toolkit
