name: pyqwen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy=2.2.6
  - matplotlib
  - transformers
  - accelerate
  - evaluate
  - datasets
  - scikit-learn
  - jupyterlab
  - ipykernel
  - ipywidgets
  - tqdm
  - torchinfo
  - optuna
  - pandas
  - pandas-stubs
  - seaborn
  - pysoundfile
  - librosa
  - num2words
  - nvidia::cuda-toolkit>=13.0
